checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  environment:
    php:
      version: 8.0.11
      ini:
        "xdebug.mode": coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      services:
        postgres: 13

      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        before:
          - sed -i "s/'pgsql:host=127.0.0.1;dbname=yiitest'/'pgsql:host=127.0.0.1;dbname=scrutinizer'/" tests/TestCase.php
          - sed -i "s/'root'/'scrutinizer'/" tests/TestCase.php
          - sed -i "s/'root-password'/'scrutinizer'/" tests/TestCase.php

        override:
          - command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
